### ISSUE TITLE
Openshift Configurations

### ISSUE THREAD

**Issue by glasnt** [WhereSoftwareGoesToDie/machiavelli#98]
Do the thing so that openshift can work with the thing

**Comment by developersteve** [comment]
seems like a thing!

**Comment by glasnt** [comment]
http://machiavelli-glasnt.rhcloud.com/

**Comment by glasnt** [comment]
[![No Maintenance Intended](http://unmaintained.tech/badge.svg)](http://unmaintained.tech/)
